public enum NetworkResult
{
    SUCCESS = 0,

    // USER

    // MERCENARY
    E_MERCENARY_INVALIED,
    E_MERCENARY_INVALIED_ID,
    E_MERCENARY_NOT_OWNED,
    E_MERCENARY_MAX_LEVEL,
    E_MERCENARY_INVALIED_LEVEL,
    E_MERCENARY_NOT_ENOUGH_GOLD,
    E_MERCENARY_ALREADY_OWNED,

}
